# Generated by Django 6.0.4 on 2026-04-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "instituicao",
                    models.CharField(default="Universidade Lusófona", max_length=200),
                ),
                ("duracao_anos", models.IntegerField()),
                ("total_ects", models.IntegerField()),
                ("descricao", models.TextField()),
            ],
        ),
    ]
