# Generated by Django 6.0.4 on 2026-04-12 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=150)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("descricao", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_decisoes", models.CharField(max_length=200)),
                ("justificacao", models.CharField(max_length=250)),
                ("correcoes", models.CharField(max_length=150)),
                ("uso_ia", models.BooleanField()),
                (
                    "foto_caderno",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("conceitos_aplicados", models.CharField(max_length=250)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
                ("video_demo", models.URLField()),
                ("github_repo", models.URLField()),
                ("data", models.DateField()),
                (
                    "classificacao",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=150)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("website_ofc", models.URLField()),
                ("descricao", models.CharField(max_length=200)),
                (
                    "classificacao",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("semestre", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("ects", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.RenameField(
            model_name="licenciatura",
            old_name="duracao_anos",
            new_name="ects",
        ),
        migrations.RenameField(
            model_name="licenciatura",
            old_name="total_ects",
            new_name="semstres",
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="instituicao",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("resumo", models.CharField(max_length=200)),
                ("aluno", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("destaque", models.BooleanField()),
                (
                    "orientador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.docente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="docente",
            name="disciplina",
            field=models.ManyToManyField(blank=True, to="portfolio.unidadecurricular"),
        ),
    ]
