# Generated by Django 6.0.4 on 2026-04-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_competencia_docente_formacao_makingof_projeto_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MakingOF",
            new_name="MakingOFF",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="semstres",
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="semestres",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
